##################################################################################################
# MODEL
##################################################################################################

model: 
    type: "half" # "full" (every joint except waist) or 
                 # "half" (only leg joints)
                 # "crawl" (leg joints, no waist, shoulder pitch, elbow)

    # model_half: "../../models/g1_12dof_obj.urdf"     # path to the URDF model of the robot
    model_half: "../../models/titan_obj.urdf"        # path to the URDF model of the robot
    # model_full: "../../models/g1_no_hands_obj.urdf"  # path to the URDF model of the robot
    # model_crawl: "../../models/titan_crawl_obj.urdf" # path to the URDF model of the robot

##################################################################################################
# REFERENCE TRAJECTORY
##################################################################################################

reference:
    
    # location of the reference trajectory file
    path: "../references/walk1_subject5.csv"
    # path: "../references/sprint1_subject2.csv"

    # nominal dt between the reference trajectory points
    hz: 20  # [sec]

reference_nodes:

    # location of nodes
    path: "../references/gen_pos_trajectory.csv"
    # path: "../references/gen_pos_trajectory_crawl.csv"

    # time between the nodes [sec], should be (num_nodes - 1)
    # T: [1.0, 
    #     5.0,
    #     1.0, 
    #     10.0, 
    #     10.0]

    # time between the nodes [sec], should be (num_nodes - 1)
    T: [5.0, 
        5.0,
        1.0, 
        10.0, 
        15.0, 
        10.0, 
        10.0, 
        3.0]

    # base z offset to the reference trajectory
    z_pos_offset: 0.035


##################################################################################################
# SIMULATION PARAMETERS
##################################################################################################

# drake simulation parameters
sim:

    duration: 60.0       # [sec], simulation duration
    # duration: 5.1       # [sec], simulation duration
    real_time_rate: 0.0  # real-time rate of the simulation
    time_step: 0.002     # [sec], simulation time step

##################################################################################################
# MPC PARAMETERS
##################################################################################################

MPC:

    # position weights
    Qq: [8.0, 8.0, 12.0, 8.0,       # base orientation
         2.0, 2.0, 2.0,                # base position
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4, # left leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4] # right leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll

    # velocity weights
    Qv: [0.4, 0.4, 0.4,                       # base orientation
         0.1, 0.1, 0.1,                       # base position
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # left leg
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08]  # right leg

    # input weights
    R: [100.0, 100.0, 100.0,                         # base orientation
        100.0, 100.0, 100.0,                         # base position
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005,    # left leg
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005]    # right leg
    
    # terminal scaling
    Qf_q_scaling: 10.0
    Qf_v_scaling: 10.0

    # standard parameters
    num_steps: 40  # number of nodes
    mpc_rate: 50   # Hz
    dt: 0.05       # time step

    # solver parameters
    max_iterations: 2
    scaling: True
    equality_constraints: False
    Delta0: 5.0
    Delta_max: 100_000
    num_threads: 20
    contact_stiffness: 2_000
    dissipation_velocity: 0.1
    smoothing_factor: 0.008
    friction_coefficient: 0.5
    stiction_velocity: 0.5
    verbose: False

MPC_full:

    # position weights
    Qq: [8.0, 8.0, 8.0, 8.0,             # base orientation
         4.0, 4.0, 2.0,                  # base position
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4,   # left leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4,   # right leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.3, 0.3, 0.3, 0.2,             # left arm: shoulder_pitch, shoulder_roll, shoulder_yaw, elbow_pitch
         0.3, 0.3, 0.3, 0.2]             # right arm: shoulder_pitch, shoulder_roll, shoulder_yaw, elbow_pitch

    # velocity weights
    Qv: [0.4, 0.4, 0.4,                       # base orientation
         0.1, 0.1, 0.1,                       # base position
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # left leg
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # right leg
         0.03, 0.03, 0.03, 0.03,              # left arm
         0.03, 0.03, 0.03, 0.03]              # right arm

    # input weights
    R: [100.0, 100.0, 100.0,                      # base orientation
        100.0, 100.0, 100.0,                      # base position
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005, # left leg
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005, # right leg
        0.001, 0.001, 0.001, 0.001,               # left arm
        0.001, 0.001, 0.001, 0.001]               # right arm
    
    # terminal scaling
    Qf_q_scaling: 10.0
    Qf_v_scaling: 10.0

    # standard parameters
    num_steps: 50    # number of nodes
    mpc_rate: 50     # Hz
    dt: 0.05        # time step

    # solver parameters
    max_iterations: 2
    scaling: True
    equality_constraints: False
    Delta0: 5.0
    Delta_max: 100_000
    num_threads: 20
    contact_stiffness: 2_000
    dissipation_velocity: 0.1
    smoothing_factor: 0.008
    friction_coefficient: 0.5
    stiction_velocity: 0.5
    verbose: False

MPC_crawl:

    # position weights
    Qq: [8.0, 8.0, 8.0, 8.0,           # base orientation
         2.0, 2.0, 2.0,                # base position
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4, # left leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4, # right leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.2, 0.2,                     # left arm: shoulder_pitch, elbow_pitch
         0.2, 0.2]                     # right arm: shoulder_pitch, elbow_pitch

    # velocity weights
    Qv: [0.4, 0.4, 0.4,                       # base orientation
         0.1, 0.1, 0.1,                       # base position
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # left leg
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # right leg
         0.03, 0.03,                          # left arm
         0.03, 0.03]                          # right arm

    # input weights
    R: [100.0, 100.0, 100.0,                         # base orientation
        100.0, 100.0, 100.0,                         # base position
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005,    # left leg
        0.001, 0.001, 0.001, 0.001, 0.005, 0.005,    # right leg
        0.001, 0.001,                               # left arm
        0.001, 0.001]                               # right arm
    
    # terminal scaling
    Qf_q_scaling: 10.0
    Qf_v_scaling: 10.0

    # standard parameters
    num_steps: 40  # number of nodes
    mpc_rate: 50   # Hz
    dt: 0.05       # time step

    # solver parameters
    max_iterations: 2
    scaling: True
    equality_constraints: False
    Delta0: 5.0
    Delta_max: 100_000
    num_threads: 20
    contact_stiffness: 2_000
    dissipation_velocity: 0.1
    smoothing_factor: 0.008
    friction_coefficient: 0.5
    stiction_velocity: 0.5
    verbose: False


##################################################################################################
# INITIAL CONFIGURATION
##################################################################################################


q0:  [1.00, 0.00, 0.00, 0.00,           # base orientation, (w, x, y, z)
      0.00, 0.00, 0.78,                 # base position, (x, y, z)
      -0.20, 0.00, 0.00, 0.42, -0.23, 0.0,  # left leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)
      -0.20, 0.00, 0.00, 0.42, -0.23, 0.0]  # right leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)

v0: [0.00, 0.00, 0.00,            
     0.00, 0.00, 0.00,                   
     0.00, 0.00, 0.00, 0.0, 0.0, 0.0,
     0.00, 0.00, 0.00, 0.0, 0.0, 0.0]  # initial velocities of the robot (base orientation, base position, left leg, right leg)


q0_full:  [1.00, 0.00, 0.00, 0.00,           # base orientation, (w, x, y, z)
           0.00, 0.00, 0.76,                 # base position, (x, y, z)
          -0.20, 0.00, 0.00, 0.42, -0.23, 0.0,  # left leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)
          -0.20, 0.00, 0.00, 0.42, -0.23, 0.0,  # right leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)
           0.00, 0.00, 0.00, 0.00, # left arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow pitch, wrist roll, wrist pitch, wrist yaw)
           0.00, 0.00, 0.00, 0.00] # right arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow pitch, wrist roll, wrist pitch, wrist yaw)

v0_full: [0.00, 0.00, 0.00,            
          0.00, 0.00, 0.00,                   
          0.00, 0.00, 0.00, 0.0, 0.0, 0.0,
          0.00, 0.00, 0.00, 0.0, 0.0, 0.0,
          0.00, 0.00, 0.00, 0.0,
          0.00, 0.00, 0.00, 0.0]

q0_crawl:  [1.00, 0.00, 0.00, 0.00,             # base orientation, (w, x, y, z)
            0.00, 0.00, 0.76,                    # base position, (x, y, z)
           -0.20, 0.00, 0.00, 0.42, -0.23, 0.0,  # left leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)
           -0.20, 0.00, 0.00, 0.42, -0.23, 0.0,  # right leg, (hip pitch, hip roll, hip yaw, knee, ankle pitch, ankle roll)
            0.00, 0.00,                          # left arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow pitch, wrist roll, wrist pitch, wrist yaw)
            0.00, 0.00]                          # right arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow pitch, wrist roll, wrist pitch, wrist yaw)

v0_crawl: [0.00, 0.00, 0.00,            
           0.00, 0.00, 0.00,                   
           0.00, 0.00, 0.00, 0.0, 0.0, 0.0,
           0.00, 0.00, 0.00, 0.0, 0.0, 0.0,
           0.00, 0.00,
           0.00, 0.00]


##################################################################################################
# PD GAINS
##################################################################################################

gains:

    Kp: [250, 250, 200, 250, 40, 40, # LHP, LHR, LHY, LKP, LAP, LAR
         250, 250, 200, 250, 40, 40] # RHP, RHR, RHY, RKP, RAP, RAR
    Kd: [2, 2, 2, 4, 2, 2, 
         2, 2, 2, 4, 2, 2]


gains_full:

    Kp: [250, 250, 200, 250, 20, 20,    # LHP, LHR, LHY, LKP, LAP, LAR
         250, 250, 200, 250, 20, 20,    # RHP, RHR, RHY, RKP, RAP, RAR
         20,  20,  20,  20,             # LSP, LSR, LSY, LEP
         20,  20,  20,  20]             # RSP, RSR, RSY, REP

    Kd: [5, 5, 5, 4, 2, 2, 
         5, 5, 5, 4, 2, 2,
         2, 2, 2, 2,
         2, 2, 2, 2]


gains_crawl:

    Kp: [250, 250, 200, 250, 20, 20,  # LHP, LHR, LHY, LKP, LAP, LAR
         250, 250, 200, 250, 20, 20,  # RHP, RHR, RHY, RKP, RAP, RAR
         20,  20,                     # LSP, LSR, LSY, LEP
         20,  20]                     # RSP, RSR, RSY, REP

    Kd: [5, 5, 5, 4, 2, 2, 
         5, 5, 5, 4, 2, 2,
         2, 2,
         2, 2]


##################################################################################################
# VISUALIZATION
##################################################################################################

# contact force visualization
contact_vis: False

# colors to use throughout the simulation
color:

    # transparent: [0.0, 0.0, 0.0, 0.0]
    # white: [1.0, 1.0, 1.0, 1.0]
    # gray: [0.5, 0.5, 0.5, 1.0]
    # caltech orange: [0.9200, 0.3896, 0.0433, 1.0] 

    # ground: [0.0, 0.0, 0.0, 0.0]
    ground: [0.5, 0.5, 0.5, 1.0]
    terrain: [0.5, 0.5, 0.5, 1.0]

