##################################################################################################
# RANDOM SEED
##################################################################################################

seed:
    fixed: False
    value: 0

##################################################################################################
# CONTROLLER
##################################################################################################

controller: 'MH'  # choose between 'MPC', 'HLIP', 'MH' (both)

##################################################################################################
# MPC PARAMETERS
##################################################################################################

MPC:

    # position weights
    Qq: [4.0, 4.0, 4.0, 4.0,  # base orientation
         1.0, 1.0, 1.0,           # base position
         0.4, 0.4, 0.4, 0.3, 0.8, # left leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
         0.1, 0.1, 0.01, 0.01,    # left arm: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch
         0.4, 0.4, 0.4, 0.3, 0.8, # right leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
         0.1, 0.1, 0.01, 0.01]    # right arm: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch

    # velocity weights
    Qv: [0.4, 0.4, 0.4,                    # base orientation
         0.1, 0.1, 0.1,                    # base position
         0.03, 0.03, 0.03, 0.03, 0.08,     # left leg
         0.01, 0.01, 0.001, 0.003,         # left arm
         0.03, 0.03, 0.03, 0.03, 0.08,     # right leg
         0.01, 0.01, 0.001, 0.003]         # right arm

    # input weights
    R: [100.0, 100.0, 100.0,       # base orientation
        100.0, 100.0, 100.0,       # base position
        0.001, 0.001, 0.001, 0.001, 0.0005, # left leg
        0.005, 0.005, 0.005, 0.005,       # left arm
        0.001, 0.001, 0.001, 0.001, 0.0005, # right leg
        0.005, 0.005, 0.005, 0.005]        # right arm
    
    # terminal scaling
    Qf_q_scaling: 10.0
    Qf_v_scaling: 10.0

    # standard parameters
    num_steps: 20  # number of nodes
    mpc_rate: 50   # Hz
    dt: 0.05       # time step

    # solver parameters
    max_iterations: 3
    scaling: True
    equality_constraints: False
    Delta0: 10.0
    Delta_max: 100_000
    num_threads: 20
    contact_stiffness: 2_000
    dissipation_velocity: 0.1
    smoothing_factor: 0.008
    friction_coefficient: 0.5
    stiction_velocity: 0.5
    verbose: False

##################################################################################################
# HLIP PARAMETERS
##################################################################################################

HLIP:

    # single support time
    T_SSP: 0.35   # [sec], single support phase duration

    # CoM height range
    z_com_upper: 0.62 # [m], upper bound for the CoM height
    z_com_lower: 0.45 # [m], lower bound for the CoM height

    # foor parameters
    z_apex: 0.08         # [m], apex height of the foot trajectory
    z_foot_offset: 0.0  # [m], overall traj offset of the foot from the ground
    bezier_order: 7      # 5 or 7, order of the bezier curve for foot traj
    hip_bias: 0.3       # [m], bias of the hip, distance foot to foot

    # maximum step lengths
    ux_max: 0.6  # [m], max forward step length
    uy_max: 0.4  # [m], max lateral step length

    # maximum magnitude command parameters
    vx_max: 0.7          # [m/s], max forward velocity
    vy_max: 0.3          # [m/s], max lateral velocity
    wz_max: 35           # [deg/s], max yaw rate

    # threshold for base velocity
    vx_base_threshold: 0.5  # [m/s], threshold for forward velocity
    vy_base_threshold: 0.4  # [m/s], threshold for lateral velocity
    wz_base_threshold: 20   # [deg/s], threshold for yaw rate

##################################################################################################
# SIMULATION PARAMETERS
##################################################################################################

# drake simulation parameters
sim:

    duration: 15.0       # [sec], simulation duration
    real_time_rate: 0.0  # real-time rate of the simulation
    time_step: 0.002     # [sec], simulation time step

##################################################################################################
# REFERENCES
##################################################################################################

# references to test tracking, assumes you start at (px,py) = (0,0)
references:

    # fix the base orientation
    fixed_base_orientation: True

    # if below is true, the base will follow a fixed velocity and z_com
    enabled: False

    # constant velocity tracking
    vx_ref: 0.3  # [m/s], forward velocity in world frame
    vy_ref: 0.0  # [m/s], lateral velocity in world frame
    
    # constant CoM height tracking
    z_com_ref: 0.63  # [m], CoM height

##################################################################################################
# DISTURBANCES
##################################################################################################

# single disturbance on the base frame
disturbance:
    
    enabled: False

    # fixed disturbance
    fixed: True
    fx: 0.0
    fy: 85.0
    fz: 0.0

    # force to be applied on the base frame is drawn uniformly from a circle
    # in the xy direction with this radius
    force_radius: 175.0  # [N]

    # time parameters
    time_applied: 2.0  # [sec], time when the disturbance is applied
    duration: 0.1      # [sec], duration of the disturbance

##################################################################################################
# ACTIVATION FUNCTION
##################################################################################################

# tanh avtication function for blending https://www.desmos.com/calculator/bwpmzor4og
# a in [0, inf], how steep the steep the transisiton is.
# p in [0,1], where the transition is located at in [0,1]

blending:
    a: 5.0
    p: 0.5

##################################################################################################
# INITIAL CONFIGURATION
##################################################################################################

# parallel legs, slighlty bent
q0:  [1.0000, -0.0000, 0.0031, -0.0000,          # base orientation, (w, x, y, z)
     -1.0000, 0.0000, 0.9501,                    # base position, (x, y, z)
      0.0000, -0.0002, -0.4752, 1.0012, -0.5245,  # left leg, (hip yaw, hip roll, hip pitch, knee, ankle)
      0.0001, 0.0000, 0.0000, 0.0000,             # left arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow)
     -0.0000, 0.0002, -0.4752, 1.0012, -0.5245,  # right leg, (hip yaw, hip roll, hip pitch, knee, ankle)
      0.0001, 0.0000, 0.0000, 0.0000]             # right arm, (shoulder pitch, shoulder roll, shoulder yaw, elbow)

v0: [0.0000, 0.0000, 0.0000,            
     0.0000, 0.0000, 0.0000,                   
     0.0000, 0.0000, 0.0000, 0.0000, 0.0000,  
     0.0000, 0.0000, 0.0000, 0.0000,           
     0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 
     0.0000, 0.0000, 0.0000, 0.0000]    

##################################################################################################
# PD GAINS
##################################################################################################

gains:

  Kp: [800, 800, 800, 900, 150, # left: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
       100, 100, 100, 100,       # left: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch
       800, 800, 800, 900, 150, # right: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
       100, 100, 100, 100]       # right: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch
  Kd: [10, 10, 10, 10, 1,        # left: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
       5, 5, 5, 5,               # left: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch
       10, 10, 10, 10, 1,        # right: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch
       5, 5, 5, 5]               # right: shoudler_pitch, shoulder_roll, shoulder_yaw, elbow_pitch

    # Adrian gains
    # 500, 1000, 500, 500, 500 (legs)
    # 10, 10, 20, 5, 2         (arms)

##################################################################################################
# LOGGING
##################################################################################################

# choose to log new data from simulation
logging: True

##################################################################################################
# VISUALIZATION
##################################################################################################

# visluaze the HLIP trajectory
HLIP_vis: False

# contact force visualization
contact_vis: False

# colors to use throughout the simulation
color:

    # transparent: [0.0, 0.0, 0.0, 0.0]
    # white: [1.0, 1.0, 1.0, 1.0]
    # gray: [0.5, 0.5, 0.5, 1.0]
    # caltech orange: [0.9200, 0.3896, 0.0433, 1.0] 

    # ground: [0.0, 0.0, 0.0, 0.0]
    ground: [0.5, 0.5, 0.5, 1.0]
    terrain: [0.5, 0.5, 0.5, 1.0]


##################################################################################################
# Terrain
##################################################################################################

# for testing the random terrain
terrain:
    
    # choose whether or not to enable the rough terrain
    enabled: False

    # parameters for generating the terrain
    num_entities: 50  # number of entities
    x_range: [1.0, 2.0]   # [m], range of the x-axis
    y_range: [-0.5, 0.5]  # [m], range of the y-axis
    r_range: [0.1, 0.15]  # [m], range of the sphere radius

##################################################################################################
# WALL
##################################################################################################

# Extra wall for the robot to brace itself against
wall: 
    enabled: False

    # Size and position
    length: 1.0  # [m]
    width: 0.1 # [m]
    height: 0.7  # [m]
    x: 0.0  # [m]
    y: 0.5  # [m] 

##################################################################################################
# MODEL ERROR
##################################################################################################

model_error:
    enabled: False

    # Change link masses by m <-- m * r, 
    # where r ~ N(mu, sigma) is a random scale factor
    mu: 1.0
    sigma: 0.2

##################################################################################################
# STATE ESTIMATION ERROR
##################################################################################################

estimation_error:
    enabled: False

    # Add Gaussian noise to the state estimate at each timestep
    # x <-- x + r, r ~ N(mu, sigma)
    mu: 0.0
    sigma: 0.02

##################################################################################################
# VISUAL OBSTACLES
##################################################################################################

# Field of a bunch of cylinders that we can manually drive around
obstacle_field:
    enabled: False

    # Number of obstacles
    num_obstacles: 10

    # Obstacle parameters
    radius_range: [0.1, 0.2]
    x_range: [1.0, 5.0]
    y_range: [-2.0, 2.0]

# A floating obstacle that we need to duck under
overhang:
    enabled: False

    # Obstacle parameters
    dimensions: [0.5, 2.0, 0.3]  # length, width, height
    position: [1.5, 0.0, 1.3]  # x, y, z

##################################################################################################
# VISUALIZATION
##################################################################################################

camera:

    # 2D Render Mode
    2D_mode: True

    # Position of the Meshcat camera in the world frame
    position: [0, -5, 1.0]

    # Where the meshcat camera is looking
    target: [0.0, 0.0, 1.0]

save_html:
    # Save the meshcat recording to an html file. This can be used to produce a
    # video later, or even shared directly with someone to play in their 
    # browser (even if they don't have Drake or meshcat installed).
    enabled: True
