##################################################################################################
# MODEL
##################################################################################################

model: 
    type: "half" # "full" (every joint except waist) or 
                 # "half" (only leg joints)
                 # "crawl" (leg joints, no waist, shoulder pitch, elbow)

    model_list: ["../../models/g1_29dof_m4_obj.urdf",
                "../../models/g1_29dof_obj.urdf"]

##################################################################################################
# REFERENCE TRAJECTORY
##################################################################################################

# CSV data with alot of points
reference:
    
    # location of nodes
    path_list: ["../references/gen_pos_1.csv",
                "../references/gen_pos_2.csv"]

    # nominal dt between the reference trajectory points
    hz: 400  # [sec]

    z_pos_offset: 0.10

##################################################################################################
# SIMULATION PARAMETERS
##################################################################################################

# drake simulation parameters
sim:

    duration: 7.0       # [sec], simulation duration
    real_time_rate: 0.0  # real-time rate of the simulation
    time_step: 0.002     # [sec], simulation time step

##################################################################################################
# MPC PARAMETERS
##################################################################################################

MPC:

    # position weights
    Qq: [4.0,  4.0, 20.0, 4.0,       # base orientation
         0.1, 0.1, 0.1,                # base position
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4, # left leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll
         0.4, 0.4, 0.4, 0.3, 0.4, 0.4] # right leg: hip_yaw, hip_roll, hip_pitch, knee_pitch, ankle_pitch, ankle_roll

    # velocity weights
    Qv: [0.4, 0.4, 0.4,                       # base orientation
         0.1, 0.1, 0.1,                       # base position
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08,  # left leg
         0.05, 0.05, 0.05, 0.05, 0.08, 0.08]  # right leg

    # input weights
    R: [100.0, 100.0, 100.0,                         # base orientation
        100.0, 100.0, 100.0,                         # base position
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001,    # left leg
        0.001, 0.001, 0.001, 0.001, 0.001, 0.001]    # right leg
    
    # terminal scaling
    Qf_q_scaling: 10.0
    Qf_v_scaling: 10.0

    # standard parameters
    num_steps: 40  # number of nodes
    mpc_rate: 50   # Hz
    dt: 0.05       # time step

    # solver parameters
    max_iterations: 2
    scaling: True
    equality_constraints: False
    Delta0: 5.0
    Delta_max: 100_000
    num_threads: 20
    contact_stiffness: 2_000
    dissipation_velocity: 0.1
    smoothing_factor: 0.008
    friction_coefficient: 0.5
    stiction_velocity: 0.5
    verbose: False

##################################################################################################
# PD GAINS
##################################################################################################

gains:

    Kp: [500, 500, 500, 500, 200, 200, # LHP, LHR, LHY, LKP, LAP, LAR
         500, 500, 500, 500, 200, 200] # RHP, RHR, RHY, RKP, RAP, RAR
    Kd: [2, 2, 2, 4, 2, 2, 
         2, 2, 2, 4, 2, 2]


##################################################################################################
# VISUALIZATION
##################################################################################################

# contact force visualization
contact_vis: False


